### ISSUE TITLE
Cannot convert non-finite values (NA or inf) to integer

### ISSUE THREAD

**Issue by dhhagan** [quant-aq/cli#21]
When running the `expunge` command, the script runs into issues if any value in the `flag` value is corrupted. 

## Example

```python

>>> quantaq-cli expunge --dry-run modulair_pm data.csv

```

## Traceback

```python

Traceback (most recent call last):
  File "/Users/davidhagan/.pyenv/versions/3.6.12/bin/quantaq-cli", line 8, in <module>
    sys.exit(main())
  File "/Users/davidhagan/.pyenv/versions/3.6.12/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/davidhagan/.pyenv/versions/3.6.12/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/davidhagan/.pyenv/versions/3.6.12/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/davidhagan/.pyenv/versions/3.6.12/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/davidhagan/.pyenv/versions/3.6.12/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/davidhagan/.pyenv/versions/3.6.12/lib/python3.6/site-packages/quantaq_cli/console/__init__.py", line 77, in expunge
    expunge_command(file, output, flagcol=flag, dry_run=dry_run, verbose=verbose, model=model, table=table, **kwargs)
  File "/Users/davidhagan/.pyenv/versions/3.6.12/lib/python3.6/site-packages/quantaq_cli/console/commands/expunge.py", line 48, in expunge_command
    df[flagcol] = df[flagcol].astype(int)
  File "/Users/davidhagan/.pyenv/versions/3.6.12/lib/python3.6/site-packages/pandas/core/generic.py", line 5548, in astype
    new_data = self._mgr.astype(dtype=dtype, copy=copy, errors=errors,)
  File "/Users/davidhagan/.pyenv/versions/3.6.12/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 604, in astype
    return self.apply("astype", dtype=dtype, copy=copy, errors=errors)
  File "/Users/davidhagan/.pyenv/versions/3.6.12/lib/python3.6/site-packages/pandas/core/internals/managers.py", line 409, in apply
    applied = getattr(b, f)(**kwargs)
  File "/Users/davidhagan/.pyenv/versions/3.6.12/lib/python3.6/site-packages/pandas/core/internals/blocks.py", line 595, in astype
    values = astype_nansafe(vals1d, dtype, copy=True)
  File "/Users/davidhagan/.pyenv/versions/3.6.12/lib/python3.6/site-packages/pandas/core/dtypes/cast.py", line 968, in astype_nansafe
    raise ValueError("Cannot convert non-finite values (NA or inf) to integer")
ValueError: Cannot convert non-finite values (NA or inf) to integer
```

**Comment by dhhagan** [comment]
Patch released with 0.4.0a1
